version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: replenit-zookeeper
    ports:
      - "3530:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      kafka_network:
        ipv4_address: 10.111.1.3

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: replenit-kafka
    ports:
      - "3531:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 10.111.1.3:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://10.111.1.2:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
    depends_on:
      - zookeeper
    networks:
      kafka_network:
        ipv4_address: 10.111.1.2

networks:
  kafka_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.111.1.0/24
          gateway: 10.111.1.1
