version: "3"

services:
  
  rabbitmq:
    container_name: replenit-rabbit
    image: rabbitmq:3.13-management
    hostname: rabbitmqhost
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - 3535:5672
      - 35035:15672
    environment:
      RABBITMQ_DEFAULT_USER: rppc4rplnt_usr
      RABBITMQ_DEFAULT_PASS: M8Nn4KU62hsyqp433dLwQeRg9
    restart: unless-stopped
    networks:
      local:
        ipv4_address: 10.111.4.3
   

volumes:
  rabbitmq_data:
    driver: local 


networks:
  local:
    driver: bridge
    ipam:
      config:
        - subnet: 10.111.4.0/24
          gateway: 10.111.4.1