version: "3"

services:
  redis:
    container_name: replenit-redis
    image: redis/redis-stack:latest
    volumes:
      - redis_data:/data
      - /docker_configs/redis/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - 3533:6379
    environment:
      - REDIS_PASSWORD=XtSJWxqdf9w24cnvuZ6kFYgaLK87HB
    command: >
      sh -c "redis-server /usr/local/etc/redis/redis.conf --requirepass $${REDIS_PASSWORD}"
    restart: unless-stopped
    networks:
      local:
        ipv4_address: 10.111.2.2

networks:
  local:
    driver: bridge
    ipam:
      config:
        - subnet: 10.111.2.0/24
          gateway: 10.111.2.1

volumes:
  redis_data:
    driver: local

